services:
  tg_bot:
    image: translator_bot_image
    container_name: translator_bot
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/translator_bot
    volumes:
      - .:/usr/src/app/translator_bot
    command: python -m main
    restart: always
    env_file:
      - .env
    stop_signal: SIGINT
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: 10
    networks:
      - translator_network
    depends_on:
      - libretranslate

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    command: ["--port", "5555", "--load-only", "en,ru"]
    restart: always
    ports:
      - "5555:5000"
    volumes:
      - libretranslate_data:/data
    networks:
      - translator_network

networks:
  translator_network:
    name: translator_network
    driver: bridge

volumes:
  libretranslate_data:
    name: libretranslate_data
